version = 1
SPDX-PackageName = "mx-port-demo-node-red"
SPDX-PackageSupplier = "info@factory-x.org"
SPDX-PackageDownloadLocation = "https://github.com/factory-x-contributions/mx-port-demo-node-red"

[[annotations]]
path = ["README.md", "doc/**", "CODE_OF_CONDUCT.md", "SECURITY.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024-2026 Contributors to the Factory-X project"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["flows.json", "lib/**", "package.json", "registeredUsers.json", "flows_cred.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024-2026 Contributors to the Factory-X project"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [".gitignore", ".gitattributes"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024-2026 Contributors to the Factory-X project"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["LICENSE_Apache-2-0.txt", "LICENSES/**", "NOTICE.txt", "THIRD-PARTY-LICENSES.txt", "AUTHORS.txt"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024-2026 Contributors to the Factory-X project"
SPDX-License-Identifier = "Apache-2.0"
